CREATE TABLE IF NOT EXISTS PRICES
(
    PRICE_ID   UUID PRIMARY KEY,
    BRAND_ID   UUID           NOT NULL,
    PRODUCT_ID UUID           NOT NULL,
    START_DATE TIMESTAMP      NOT NULL,
    END_DATE   TIMESTAMP      NOT NULL,
    PRIORITY   INTEGER        NOT NULL,
    PRICE      DECIMAL(38, 2) NOT NULL,
    CURRENCY   VARCHAR(255)   NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_brand_id ON PRICES (BRAND_ID);

CREATE INDEX IF NOT EXISTS idx_product_id ON PRICES (PRODUCT_ID);