CREATE TABLE PRICES
(
    PRICE_ID   UUID PRIMARY KEY,
    BRAND_ID   UUID           NOT NULL,
    PRODUCT_ID UUID           NOT NULL,
    START_DATE TIMESTAMP      NOT NULL,
    END_DATE   TIMESTAMP      NOT NULL,
    PRIORITY   INTEGER        NOT NULL,
    PRICE      DECIMAL(10, 2) NOT NULL,
    CURRENCY   VARCHAR(3)     NOT NULL
);